// source/src/components/InfiniteTable/components/ScrollbarPlaceholder.vue
<template>
  <div v-if="variant === 'horizontal' && scrollbarWidth">
    <div
      data-name="horizontal-scrollbar-placeholder"
      :style="{
        position: 'absolute',
        overflow: 'visible',
        overflowX: 'scroll',
        bottom: 0,
        ...style
      }"
    />
  </div>
  <div v-else-if="variant === 'vertical' && scrollbarWidth">
    <div
      data-name="vertical-scrollbar-placeholder"
      :style="{
        position: 'absolute',
        overflow: 'visible',
        overflowY: 'scroll',
        bottom: 0,
        ...style
      }"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { getScrollbarWidth } from '../../utils/getScrollbarWidth';

interface Props {
  variant: 'horizontal' | 'vertical';
  style?: Record<string, any>;
}

const props = withDefaults(defineProps<Props>(), {
  style: () => ({})
});

// Use the shared utility function
const scrollbarWidth = computed(() => getScrollbarWidth());
</script>

// source/src/components/Table/components/ScrollbarPlaceholder.tsx
import * as React from 'react';
import { getScrollbarWidth } from '../../utils/getScrollbarWidth';

function HorizontalScrollbarPlaceholderFn(props: {
  style: React.CSSProperties;
}) {
  const height = getScrollbarWidth();

  if (!height) {
    return null;
  }
  return (
    <div
      data-name="horizontal-scrollbar-placeholder"
      style={{
        position: 'absolute',
        overflow: 'visible',
        overflowX: 'scroll',
        height,
        bottom: 0,
        ...props.style,
      }}
    ></div>
  );
}

export const HorizontalScrollbarPlaceholder = React.memo(
  HorizontalScrollbarPlaceholderFn,
);

function VerticalScrollbarPlaceholderFn(props: { style: React.CSSProperties }) {
  const width = getScrollbarWidth();

  if (!width) {
    return null;
  }
  return (
    <div
      data-name="vertical-scrollbar-placeholder"
      style={{
        position: 'absolute',
        overflow: 'visible',
        overflowY: 'scroll',
        width,
        bottom: 0,
        ...props.style,
      }}
    ></div>
  );
}

export const VerticalScrollbarPlaceholder = React.memo(
  VerticalScrollbarPlaceholderFn,
);
