// source/src/components/InfiniteTable/components/CheckBox.tsx
import * as React from 'react';
import { useEffect, useRef } from 'react';
import { join } from '../../../utils/join';
import {
  ForwardPropsToStateFnResult,
  getComponentStateRoot,
  useComponentState,
} from '../../hooks/useComponentState';
import { NonUndefined } from '../../types/NonUndefined';
import { CheckBoxCls } from './CheckBox.css';

export type InfiniteCheckBoxPropChecked = true | false | null;
export type InfiniteCheckBoxProps = {
  disabled?: boolean;
  checked?: InfiniteCheckBoxPropChecked;
  defaultChecked?: InfiniteCheckBoxPropChecked;
  onChange?: (checked: InfiniteCheckBoxPropChecked) => void;
  domProps?: React.HTMLProps<HTMLElement>;
};

export type InfiniteCheckBoxMappedState = {
  checked: NonUndefined<InfiniteCheckBoxProps['checked']>;
  disabled: NonUndefined<InfiniteCheckBoxProps['disabled']>;
  domProps: InfiniteCheckBoxProps['domProps'];
};

function forwardProps(): ForwardPropsToStateFnResult<
  InfiniteCheckBoxProps,
  InfiniteCheckBoxMappedState,
  any
> {
  return {
    checked: 1,
    disabled: (disabled) => disabled ?? false,
    domProps: 1,
  };
}

export interface InfiniteCheckBoxState extends InfiniteCheckBoxMappedState {}

const InfiniteCheckBoxRoot = getComponentStateRoot({
  // @ts-ignore
  forwardProps,
  // @ts-ignore
  // mapPropsToState,
  // @ts-ignore
  // cleanup: cleanupState,
  // @ts-ignore,
  mappedCallbacks: {
    checked: (checked) => {
      return {
        callbackName: 'onChange',
        callbackParams: [checked],
      };
    },
  },

  debugName: 'InfiniteCheckBox',
});

function InfiniteCheckBoxComponent() {
  const { componentState, componentActions } =
    useComponentState<InfiniteCheckBoxState>();

  const { checked, domProps, disabled } = componentState;

  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    inputRef.current!.indeterminate = checked == null;
  }, [checked]);

  return (
    <input
      {...domProps}
      className={join('InfiniteCheckBox', CheckBoxCls, domProps?.className)}
      type="checkbox"
      ref={inputRef}
      checked={!!checked}
      disabled={disabled}
      onChange={() => {
        if (disabled) {
          return;
        }
        componentActions.checked = !checked;
      }}
    />
  );
}

export function InfiniteCheckBox(props: InfiniteCheckBoxProps) {
  return (
    <InfiniteCheckBoxRoot {...props}>
      <InfiniteCheckBoxComponent />
    </InfiniteCheckBoxRoot>
  );
}

// source/src/components/InfiniteTable/components/CheckBox.vue
<template>
  <input
    v-bind="domProps"
    :class="inputClass"
    type="checkbox"
    ref="inputRef"
    :checked="!!checked"
    :disabled="disabled"
    @change="handleChange"
  />
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { join } from '../../../utils/join';
import { CheckBoxCls } from './CheckBox.css';
import type { InfiniteCheckBoxProps, InfiniteCheckBoxPropChecked } from './CheckBox';

interface Props extends InfiniteCheckBoxProps {}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
  checked: null,
  domProps: () => ({})
});

const emit = defineEmits<{
  change: [checked: InfiniteCheckBoxPropChecked];
}>();

const inputRef = ref<HTMLInputElement>();

// Computed class for the input
const inputClass = computed(() => 
  join('InfiniteCheckBox', CheckBoxCls, props.domProps?.className)
);

// Handle checkbox state changes
const handleChange = () => {
  if (props.disabled) {
    return;
  }
  const newChecked = !props.checked;
  emit('change', newChecked);
};

// Watch for checked state changes to handle indeterminate
watch(() => props.checked, (checked) => {
  if (inputRef.value) {
    inputRef.value.indeterminate = checked == null;
  }
}, { immediate: true });
</script>
